### ISSUE TITLE
Registration to Login flow could be improved

### ISSUE THREAD

**Issue by jcsackett** [bookieio/Bookie#150]
When I registered, it then asked me to login. It should either just log me in or redirect me to the login page and then notify me that I'm registered and now need to login.

**Comment by mitechie** [comment]
Right now this is using JS and the api in order to do the activation. We should just do it in Python on the server side so that the activation form posts, we can log in the user in the back end, and then redirect them to their home bookmark page. 

In order to stop using the api, we need to verify that the test coverage is good really good there. Part of the reason for using the api in the front end was to keep down the potential usage paths, but it's hurting UX here.
