### ISSUE TITLE
I suggest to create Bookie package on pypi.python.org

### ISSUE THREAD

**Issue by harobed** [bookieio/Bookie#179]
Hi,

I suggest to create Bookie package on pypi.python.org

Best regards,
Stephane

**Comment by mitechie** [comment]
I've often thought about it, but in order to get Bookie to work you need so much tooling around it that I've avoided it so far. Getting things like paths working from package data, the JS build system and combo loader stuff outside of bookie itself, etc.

So I'm open to a discussion on how best to work on this, but going to mark this as wishlist unless I'm missing the tricks needed to make it a full python package I can submit with working install/setup instructions from pip install on through.

**Comment by mitechie** [comment]
I think we can work on taking some of the work and creating bookie-like libs in pypi. Our api client, breadability, etc are up there. I don't think Bookie itself will be pypi enabled as it's too much to get it working that way.
