### ISSUE TITLE
Why don't use Pyramid Mailer instead lib/message.py ?

### ISSUE THREAD

**Issue by harobed** [bookieio/Bookie#184]
Hi,

why don't use http://packages.python.org/pyramid_mailer/ instead https://github.com/mitechie/Bookie/blob/develop/bookie/lib/message.py ?

Best regards,
Stephane

**Comment by mitechie** [comment]
Thanks for the suggestion. It might be something to look into but you ask specifically why I don't use it.
1. It came out not long before the code in question started. (Feb 2011 vs July 2011) 
2. It doesn't seem that active currently. There's an open pull request from Chris and no changes since March of last year. It seems it was worked on for a couple of months and hasn't changed since.
3. I don't like pulling dependencies specific to the framework. I want to be able to email and pull code into celery tasks, cron scripts, etc. This seems to pull in more requirements, and while things like the queue look handy, moving emails to celery tasks gets me the same idea. 

So in the end, I'm open to the suggestion, but the lack of activity doesn't make me feel warm and fuzzy for picking it up.
