### ISSUE TITLE
Is this javascript "tag selector" can be usefull for Bookie ?

### ISSUE THREAD

**Issue by harobed** [bookieio/Bookie#186]
Is this javascript "tag selector" can be usefull for Bookie ?

http://documentcloud.github.com/visualsearch/

Best regards,
Stephane

**Comment by mitechie** [comment]
Thanks, but this would required a lot of dependencies that we don't currently use.

jQuery 1.4+, jQuery UI, Underscore.js, Backbone.js

The JS is currently written in YUI and the tag control is a custom made one since existing YUI based ones were found lacking in testing and design. 

I'm all for filing bugs against the current tag selector if there are features lacking that you liked in this one you suggest.
