### ISSUE TITLE
[Auth] Authentication of Username should not Case Sensitive.

### ISSUE THREAD

**Issue by edwardchanjw** [bookieio/Bookie#211]
For example, as my User ID.

> EdwardChanJW - login successful
> edwardchanjw - login failed

I assumes that the live of bookies are in sync with github issues of Bookie. I only search open issues for duplicate.

**Comment by mitechie** [comment]
Thanks for the report. I talked this over with some other users and want to document the consensus on how to handle things:
- All logins should check/verify the username in a case sensitive way
- The urls and uses of the username should be lower cased
- Because usernames are lower cased for all uses after login, there should only be one user per lower cased username string

**Comment by mitechie** [comment]
Reopening. The migration won't run on postgres because it's enforcing all the good requirements that the username matches values in other tables and such. So the usernames have to be lowercased in all tables with a username, like bmarks, etc.

**Comment by mitechie** [comment]
Below is the start of a migration that will make postgres happier, but the other tables aren't there yet.  

```
sel = sa.select([users])
for user in connection.execute(sel):
    stmt = users.update().\
               where(users.c.username == user['username']).\
               values(username=sa.func.lower(user['username']))
    connection.execute(stmt)
```

**Comment by mitechie** [comment]
Got it updated with updated script located: https://github.com/bookieio/Bookie/blob/develop/dbversions/versions/44dccb7b8b82_update_username_to_l.py

Took some work to get right and some downtime oh well.
