### ISSUE TITLE
Problem editing tags - pressing save doesn't always save

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#225]
I'm using bmark.us currently and I was editing some bookmarks this morning to change their tags. I got to the bookmark edit screen and clicked on a couple of tags to remove them and then typed in a new tag name and pressed save. I went back to the bookmark and the removed tags were gone, but my new tag was missing. I tried again and pressed return and then got the nice icon over the tag, but it turns out that wasn't it either.  I've experimented with using tags that have underscores in them and not and nothing seems to allow me to add a new tag that doesn't exist. However adding tags that already exist works.

**Comment by jpschewe** [comment]
When using the extension for chrome if I type in the new tag name in the list of tags and then tab to the next field and shift tab back, then the new tag shows up with the nice icon and saving from there makes the change.

**Comment by mitechie** [comment]
Thanks for the report. I'm hacking on bookie this holiday weekend and will see if I can replicate and perhaps fix.

**Comment by mitechie** [comment]
I got a chance to peek at this. It's an issue in that the tag control normally waits a fraction of a second to make sure you're done typing before it adds the tag to the input control. When you hit submit on that form, it doesn't take that into account so it's a race to see when the control gets added and the form actually does the POST to the next page.

You can see this because if you use the space to mark the completion of a tag, then hit enter, or then hit the submit button it will work. 

If you start to enter a tag and then directly hit enter or click on the submit button, it will fail to add. 

I'll work on a fix which will catch the submit event on the form in the page itself and make sure the tag control is up to date before proceeding.
