### ISSUE TITLE
Signup process needs some love 

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#266]
It still talks about being in alpha, needing an invite, etc. It's not friendly for new users.

**Comment by aka001** [comment]
I want to work on this issue. Kindly describe what should we exactly do in this ticket?

**Comment by mitechie** [comment]
Some of it is textual. 
- Bookie isn't alpha, that note should be pulled out
- You don't need an invite to get into bookie any more. That should be pulled out
- Once you click the activate link in your email and set a password, bookie should auto log you in and show you the page for your bookmarks.

**Comment by badanomaly** [comment]
If nobody is working on this issue I would like to start working on it.

**Comment by aka001** [comment]
yaa continue on it. :)

**Comment by rakeshmahadasa** [comment]
There are problems with signup. I dont know whether Im the only one facing the problem 
1. Confirmation link is not being delivered 

2.Even some valid email addresses like ( coders.infinitum@gmail.com ) are marked as invalid as an invalid email error is being generated when trying to use forgot password option

**Comment by mitechie** [comment]
On Tue, 04 Mar 2014, Rakesh Mahadasa wrote:

> There are problems with signup. I dont know whether Im the only one facing the problem
> 1. Confirmation link is not being delivered
>    2.Even some valid email addresses like ( coders.infinitum@gmail.com ) are
>    marked as invalid as an invalid email error is being generated when
>    trying to use forgot password option

Is this in a local environment? You have to run the 'make smtp' to runa
fake email server. That output needs to be base64 decoded to view the
email.

https://github.com/bookieio/Bookie/blob/develop/bookie/views/api.py#L713

Shows the code for checking the email. Can you note what message
specifically you're hitting?

## 

Rick Harding
@mitechie
http://blog.mitechie.com
http://lococast.net

**Comment by rakeshmahadasa** [comment]
Sorry My bad Im submitting "," instead of "."
Now with the email part corrected Its working as expected
but still Im not getting the conformation email. I did signup using two emails till now 
1.infintum.rakesh@gmail.com
2.coders.infinitum@gmail.com

I didn't get conformation emails. Im not using local environment. 
I faced the same problem initially ( rakeshnitcalicut@gmail.com ) and then you manually deleted my entry and asked me to signup again and I got conformation mail from your email address.

**Comment by mitechie** [comment]
On Tue, 04 Mar 2014, Rakesh Mahadasa wrote:

> Sorry My bad Im submitting "," instead of "." with the email part corrected Its working as expected
> but still Im not getting the conformation email. I did signup using two emails till now
> 1.infintum.rakesh@gmail.com
> 2.coders.infinitum@gmail.com
> 
> I didn't get conformation emails. Im not using local environment.  I
> faced the same problem initially and then you manually deleted my entry
> and asked me to signup again and I got conformation mail from your email
> address.

Ah sorry, you should be seeing the emails. Looks like the back end had a
fit and needed to be restarted.

Thanks for the heads up and emails.

## 

Rick Harding
@mitechie
http://blog.mitechie.com
http://lococast.net

**Comment by rakeshmahadasa** [comment]
Regarding the signup process I think we better have a "confirm password" option 
and when a user is trying to register with a username which already exists.. instead of showing "username already exists" warning we are getting an 502 Bad request error page. 

I would like to work on the above Modifications.

And When a user enters the username and password we are redirected to the home page so one of the modifications expected earlier were done I suppose. so will work on the other minute things expected.

Is there anything you would suggest rick. That would be of great value.

Thank you.

**Comment by mitechie** [comment]
On Tue, 04 Mar 2014, Rakesh Mahadasa wrote:

> Regarding the signup process I think we better have a "confirm password" option

This is intentional. When you signup you enter your password. 99% of the
time you can enter it correctly. If you don't, you can immediately go to
the 'forgot' password option to update it and try again. The other 99% of
people never have to both with the duplicate fields. It's an experiment, in
a way, but one that I think has been rather successful. I've only had once,
that I can recall, where a user had an issue and then ended up getting into
their account just fine.

> and when a user is trying to register with a username which already
> exists.. instead of showing "username already exists" warning we are
> getting an 502 Bad request error page.
> 
> I would like to work on the above Modifications.

Hmm, that sounds like a bug. Please file that with steps to reproduce. If
you'd like to work on that it sounds great. Let me know if you need help
getting started. Most of the authentication chain is well tested in the
api.py, test_api.py, and the JavaScript tests.

## 

Rick Harding
@mitechie
http://blog.mitechie.com
https://bmark.us
