### ISSUE TITLE
support export to csv and xml

### ISSUE THREAD

**Issue by alexlehm** [bookieio/Bookie#521]
I think it would be nice if the export could be processed by other programs, the bookmark html format doesn't work very well with that.

csv would be nice to process the bookmarks with excel or openoffice or xml would be nice for almost anything else including reading the file with perl or python

Also a better readable html export would be nice with the tags and public/private attributes visible

**Comment by mitechie** [comment]
There's an export via the API you can use which outputs JSON. This should be able to be used for most other programming purposes.

http://docs.bmark.us/en/latest/api/user.html#username-bmarks-export

It also includes the readable text now I believe. It's been a while since I updated it.

If you really need csv/xml (aside from the normal htm export from the webui) let me know, but will close this as there's already a pretty programming happy format for export use.

**Comment by mitechie** [comment]
Hmm, except I'm getting an error on api export atm with a 

```
TypeError: unable to add header to the response
```

I'll file a bug for that.

**Comment by alexlehm** [comment]
thanks, json is probably good for any case
