### ISSUE TITLE
can't see chrome icon using a dark theme

### ISSUE THREAD

**Issue by widox** [bookieio/Bookie#76]
The "B" extension icon is barely visible when using a black theme.

**Comment by mitechie** [comment]
Ok, the update isn't pretty, but with my limited graphic skill this is the best I can do is to backlight it in white so that it shows up at least. I'd LOVE for someone with a better idea to come along and try something better. I tried making the text stand upon a button square shape that would help bring it forward on a dark theme, but I can't get a darn button to come in right for nothing in inkscape.

**Comment by mitechie** [comment]
https://github.com/mitechie/Bookie/blob/develop/bookie/static/images/logo.128.svg is the inkscape file in case anyone wants to try.

**Comment by brousch** [comment]
The logo doesn't look right on my computer. My guess is that you have a Bookie font installed. I would need that font to edit the SVG properly.

**Comment by mitechie** [comment]
Yea, it requires the Cabin Sketch font from the google web fonts. I'm working on finding someone to make a better effort in some design places. We'll see what comes of it.
