### ISSUE TITLE
Add "used last time" list of tags when adding new bookmark

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#90]
I routinely have a few pages that I bookmark that are all on the same topic and thus share a lot of tags. It would be nice to have a "used last time" list of tags.

Diigo in Fx does this well. It has the list of tags used last time above the tag input box that you can click on one by one. Of course, you can also add others in the text box.

**Comment by mitechie** [comment]
Makes sense, we can add a param to the api call for /bmarks/get here:
https://github.com/mitechie/Bookie/blob/develop/bookie/views/api.py#L172

if 'get_last_tags=true' is set in the url, then if the bookmark is not found (therefore this is a new one) we can fetch the last tag_str from the last bookmark stored for a specific user and send it back in the json. This can them be put into the ui with a [copy] link to drop those into the tag box.

**Comment by mitechie** [comment]
After further thought and testing, we should make the link of the previous tags unique. So that you have to click each link to add it to the tags field one by one. By removing the words as you click them, we can make clicking fast so that you don't have to move the mouse. Should be a nice middle ground.

**Comment by mitechie** [comment]
added to the latest 0.3.3 extension
