### ISSUE TITLE
Bookmark folders

### ISSUE THREAD

**Issue by silopolis** [bookieio/Bookie#95]
Hi,

It would be great to have some kind of hierarchical filling of bookmarks wether it is a separate thing or a way to select tags and arrange them in a hierarchy.

Bests

**Comment by mitechie** [comment]
Hmm, I'm not following the use case. So let's say I have bookmarks tagged python, and some of those with sqlalchemy. You want to see a nested structure with python at the root and sqlachemy nested as a part of a tree or something? 

What do you use this for? You can supply multiple tags into the main filter bar, and we do help autocomplete those based on what other tags have those bookmarks, which seems part of this, but without the tree view?

**Comment by silopolis** [comment]
May be this is because my brain seem funnel shaped, but I like hierarchies because they provide structuration, which often help my understanding of things and help me remember of things. Hierarchical folders/topics/categories can also provide a different taxonomy/classification scheme. On the other hand, they often reveal to rigid on complex subjects where you'd like to have several hierarchies or have items in several branches of the tree. Being able to create hierachies based on selected tags seemed a way be able to create multiple dynamic taxonomies.

So about your python/sqlalchemy example, yes, this is it. This is what delicious does btw in the sidebar of the browser extension, but only with one sublevel.

As for the search bar, autocompletion is great and works just like it should ! But as an example, if I click on a "git" tag, I get bkmks tagged with it, fine. Then I want to drill down my search to git howtos, I click on a "howto" tag... no luck, I get all links tagged with "howto", wether they're tagged with "git" or not. Don't get me wrong, this is a perfectly understandable and good behaviour, but in this case, what I miss is like in delicious, the possibility to select tags one after the other to funnel their selection.

**Comment by mitechie** [comment]
Ah ok, thanks for the time clarifying. I wonder if the easiest method to help bootstrap the idea would be to look back at what the links in the tags do.

Maybe instead of going to a page full of links with that tag, they actually enter that tag into the fitler at the top of the page. Each consecutive click would add another tag to the filter. So it would act as if you typed it, just via a click mechanism instead. It sounds like this would allow you to 'drill down' with the mouse like you're wanting perhaps?

I'll revisit my old delicious account and see what their sidebar is as a matter of comparison as well. 

In the end, I've tried to construct bookie under the idea that search is more powerful than lists, tag clouds, etc. So it's kind of structured and build towards that end as an up front design decision.

**Comment by mitechie** [comment]
So revisiting this, the new TagControl works as we discussed. As you click the tags listed on a bookmark, the page adds that tag and reloads on the fly. I think this implements enough of what you had been looking for. Let me know if that's not true.
